In [1]:
import
from array import *

arr = ('i', [1,2,3,4])
print(arr)


('i', [1, 2, 3, 4])


In [6]:
import array
from array import *
arr = array('i',[1,2,3,4])
print(arr)


array('i', [1, 2, 3, 4])


In [4]:
type(arr)

array.array

In [18]:
import numpy as np

In [19]:
arr1 = np.array([1,2,3,4,5])
print(arr1)
type(arr1)

[1 2 3 4 5]


numpy.ndarray

In [20]:
import numpy as np

arr1 = np.array((1,2,3,4,5))
print(arr1)
type(arr1)

[1 2 3 4 5]


numpy.ndarray

In [42]:
arr = np.array(range(10))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
# start, stop, step

arr4 = np.arange(0,20,2)
arr4

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [40]:
arr5 = np.random.rand(3,3)
arr5

# rand fucntion gives values 0 to 1 . 1 is excluded

array([[0.95794258, 0.65374913, 0.05009819],
       [0.31882833, 0.99534943, 0.60381738],
       [0.52334227, 0.94837291, 0.40892086]])

In [39]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [37]:
full = np.full((4,3),5)
full

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [47]:
# diagonal matrices
arr6 = np.diag([1,2,3,4,5,6])
arr6

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [45]:
arr7 = np.random.rand(5,5)
print(arr+10)

[10 11 12 13 14 15 16 17 18 19]


In [46]:
arr7 = np.random.rand(5,5)
print(arr-10)

[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1]


In [48]:
arr7 = np.random.rand(5,5)
print(arr*10)

[ 0 10 20 30 40 50 60 70 80 90]


In [50]:
import numpy as np
arr8 = np.array(range(100)).reshape((10,10))
arr8

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [55]:
print(arr8[5][5])

55


In [58]:
# one more consisle
print(arr([1:3],[ 4:6])
dd


SyntaxError: invalid syntax (133011787.py, line 2)

In [1]:
# 26 copy and view

In [2]:
# 28 iterating over array



In [6]:
import numpy as np
arr2 = np.array([9,8,7,6,5,4,3])
arr2


array([9, 8, 7, 6, 5, 4, 3])

In [7]:
type(arr2)

numpy.ndarray

In [12]:
# iterating over array
for i in arr2:
    print(i)

9
8
7
6
5
4
3


In [13]:
# creating 2d array

In [18]:

arr3 = np.array([[9,8,7,6,5,4,3], [1,2,3,4,5,6,7]])
arr3


array([[9, 8, 7, 6, 5, 4, 3],
       [1, 2, 3, 4, 5, 6, 7]])

In [23]:
# this is wrong
for i in arr3:
    print(i)

[9 8 7 6 5 4 3]
[1 2 3 4 5 6 7]


In [21]:
# this is correct
# how to iterate over 2nd array and so on...

for i in arr3:
    for j in i:
        print(j)

9
8
7
6
5
4
3
1
2
3
4
5
6
7


In [24]:
# joining arrays =  order of array should be same.

In [32]:
# merge ke liye ek common thing hone chahiye
# join means order ( row, column) same. so we can extend. extend can horizontally or vertivally. 
# add me kuch bi same ni hota.

In [ ]:
# make 2   1d array.

In [33]:
arr2 = np.array([1,2,3])
arr2


array([1, 2, 3])

In [34]:
arr3 = np.array([3,4,5,6])
arr3

array([3, 4, 5, 6])

In [45]:
a = np.concatenate((arr2,arr3), axis = 0)
print(a)

[1 2 3 3 4 5 6]


In [ ]:
# note in 1d no axis. only x axis no y . becoz y means 2d

In [42]:
# make 2d array

arr4 = np.array([[3,4,5,6],[7,8,9,0]])
arr4

array([[3, 4, 5, 6],
       [7, 8, 9, 0]])

In [44]:
arr5 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr5)

[[1 2 3 4]
 [5 6 7 8]]


In [49]:
a = np.concatenate((arr4,arr5), axis = 0)
print(a)

[[3 4 5 6]
 [7 8 9 0]
 [1 2 3 4]
 [5 6 7 8]]


In [50]:
a = np.concatenate((arr4,arr5), axis = 1)
print(a)

[[3 4 5 6 1 2 3 4]
 [7 8 9 0 5 6 7 8]]


In [54]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a)


[1 2 3 4]


In [55]:
print(b)

[5 6 7 8]


In [57]:
new_arr = np.stack((a,b), axis = 0)
new_arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [59]:
new_arr = np.stack((a,b), axis = 1)
new_arr

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [60]:
# difference bet join conccate and spilit
# copy and view

In [ ]:
# questn : 1 fill in the blanks.
# make 1d array or 2d array