In [1]:
# q1

In [4]:
import numpy as np
var = np.array([4,3,5,2,1,6,7,8,9])
var

array([4, 3, 5, 2, 1, 6, 7, 8, 9])

In [5]:
type(var)

numpy.ndarray

In [16]:
# q2

import numpy as np
var1 = np.array([[1,2],[15,6]])
var1

array([[ 1,  2],
       [15,  6]])

In [ ]:
# q3

In [29]:
import numpy as np
ar = np.array([1,2,3,4])
ar

array([1, 2, 3, 4])

In [27]:
sum = f"add by 2 is : {ar+2}"
sum

'add by 2 is : [3 4 5 6]'

In [24]:
sub = f"sub by 2 is : {ar-2}"
sub


'sub by 2 is : [-1  0  1  2]'

In [32]:
mul = f"mul by 2 is : {ar*2}"
mul

'mul by 2 is : [2 4 6 8]'

In [31]:
div = f"div by 2 is : {ar/2}"
div

'div by 2 is : [0.5 1.  1.5 2. ]'

In [ ]:
# q 4

In [40]:
# 1d
import numpy as np
ar1 = np.array([1,2,3,4])
ar1


array([1, 2, 3, 4])

In [41]:
np.max(ar1)

4

In [42]:
np.min(ar1)

1

In [43]:
np.mean(ar1)

2.5

In [44]:
# 2d

In [51]:
import numpy as np
ar2 = np.array([[1,2,3,4],[5,6,7,8]])
ar2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [52]:
np.max(ar2)

8

In [53]:
np.min(ar2)

1

In [54]:
np.mean(ar2)

4.5

In [59]:
# question 5

In [57]:
import numpy as np
ar1 = np.array([1,2,3,4])
ar1
ar1[2]

3

In [60]:
# quest 6

import numpy as np
ar1 = np.array([[1,2,3,4],[5,6,7,8]])
ar1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [61]:
ar1[1:]

array([[5, 6, 7, 8]])

In [ ]:
# que 2 using arange and reshape

In [66]:
var4 = np.arange(4).reshape(2,2)
var4

array([[0, 1],
       [2, 3]])

In [69]:
# que 2 using rand
np.random.rand(2,2)

array([[0.22669303, 0.51812255],
       [0.8514247 , 0.12222071]])

In [71]:
np.random.rand(2,2)

array([[0.39241762, 0.47423749],
       [0.58188178, 0.27209566]])

In [73]:
np.random.randint(5,20,5)

array([16, 17, 13, 17, 14])