In [1]:
import numpy as np
arr = np.array([[1,2,3,4], [5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
print(arr.ndim)

2


In [3]:
print(arr.size)

8


In [5]:
print(arr.shape)

(2, 4)


In [6]:
print(arr.dtype)

int32


In [9]:
print(type(arr))

<class 'numpy.ndarray'>


In [15]:
arr1 = np.zeros([2,2])
print(arr1)

[[0. 0.]
 [0. 0.]]


In [17]:
arr1 = np.ones([2,2])
print(arr1)

[[1. 1.]
 [1. 1.]]


In [18]:
# image analytics

In [21]:
# random( in detail lates)

In [20]:
arr2 = np.random.random([2,3])
arr2

array([[0.15271417, 0.54169886, 0.45854986],
       [0.99981584, 0.68176382, 0.73510204]])

In [30]:
arr3 = np.arange(0,30,5)
arr3


array([ 0,  5, 10, 15, 20, 25])

In [31]:
# press shift + tab in jupyter == open documentation.

In [35]:
# evenly = means diff b/t 1st and 2nd element is equal to next element.
# means sbka diff same hoga

In [36]:
arr4 = np.linspace(0,30,5)
arr4

array([ 0. ,  7.5, 15. , 22.5, 30. ])

In [40]:
# reshape
arr5 = np.array([1,2,3,4])
arr5

array([1, 2, 3, 4])

In [61]:
arr5 = arr5.reshape(2,2)
arr5


array([[1, 2],
       [3, 4]])

In [62]:
arr5.ndim

2

In [68]:
arr6 = arr5.reshape(2,2,1)
arr6


array([[[1],
        [2]],

       [[3],
        [4]]])

In [66]:
arr6.ndim

3

In [79]:
# flatten
# flat horizontal
# makes 1d array
arr7 = np.array([[[1,2,3,4],[5,6,7,8], [9,10,11,12]])
arr7

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [80]:
arr8 = arr7.flatten()
arr8

array([1, 2, 3, 4, 5, 6, 7, 8])

# array indexing (next class)

In [6]:
# 1

In [4]:
a = np.random.random([3,3])
print(a)

[[0.27443224 0.38164248 0.93348832]
 [0.68882358 0.21249627 0.76193516]
 [0.56564743 0.26985796 0.48520753]]


In [13]:
# 2
arr2 = np.random.random([4,4])
arr2

array([[0.51022617, 0.2344043 , 0.52130086, 0.24505376],
       [0.7549673 , 0.15586799, 0.69618302, 0.06019671],
       [0.7323878 , 0.90666824, 0.09319396, 0.03337211],
       [0.26912573, 0.33247475, 0.79357205, 0.30475625]])

In [14]:
resh = arr2.reshape(2,8)
resh

array([[0.51022617, 0.2344043 , 0.52130086, 0.24505376, 0.7549673 ,
        0.15586799, 0.69618302, 0.06019671],
       [0.7323878 , 0.90666824, 0.09319396, 0.03337211, 0.26912573,
        0.33247475, 0.79357205, 0.30475625]])

In [15]:
resh = arr2.reshape(1,16)
resh

array([[0.51022617, 0.2344043 , 0.52130086, 0.24505376, 0.7549673 ,
        0.15586799, 0.69618302, 0.06019671, 0.7323878 , 0.90666824,
        0.09319396, 0.03337211, 0.26912573, 0.33247475, 0.79357205,
        0.30475625]])

In [16]:
# 3
arr3 = np.array([[1,2,3,4],[5,6,7,8]])
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
# access 1st row

arr3[0,:]

array([1, 2, 3, 4])

In [39]:
# access 2 columns
arr3[:,(2,3)]


array([[3, 4],
       [7, 8]])

In [41]:
# 4
arr4 = np.array([[1,2,3,4],[5,6,7,8]])
arr4

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [47]:
print(f"2nd row 3rd col element is : {arr4[1,3]}")


2nd row 3rd col element is : 8


In [50]:
# 5
arr5 = np.array([1,2,3,4])
arr6 = np.array([5,6,7,8])
print(f"addition: {arr5+arr6}")

addition: [ 6  8 10 12]


In [52]:
# 6

arr5 = np.array([1,2,3,4])
arr6 = np.array([5,6,7,8])
print(f"multiply {arr5*arr6}")

multiply [ 5 12 21 32]


In [72]:
# 7
arr10 = np.array([1,2,3,4])
arr11 = np.array([5,6,7,8])
concat = np.concatenate((arr10,arr11),axis=0)
concat

array([1, 2, 3, 4, 5, 6, 7, 8])

In [54]:
# 8
arr7 = np.array([1,2,3,4])
arr8 = np.array([5,6,7,8])
stk = np.vstack([arr7,arr8])
stk

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [80]:
# 9

arr14=np.array([[0,1,2,3,4],
                 [3,5,6,3,2],
                 [9,6,7,8,0],
                 [1,3,2,5,4],
                 [6,4,7,9,8]])
new_arr5=np.array_split(arr14,4)
print(new_arr5)

[array([[0, 1, 2, 3, 4],
       [3, 5, 6, 3, 2]]), array([[9, 6, 7, 8, 0]]), array([[1, 3, 2, 5, 4]]), array([[6, 4, 7, 9, 8]])]


In [1]:
# normalize = (col-mean)/std

In [3]:
# # 15
# you have two datasets: ataset1 and dataset2, each containing observations of two features. want to perform the following operations. 
# 1. create numpy arrays from these datasets 
# 2. normalize both arrays
# 3 compute the mean and standard deviation for each feature.
# 4 . subtract the means and divide by standard deviation for each feature in both datasets
# 5. concatenate the normalized datasets along the column axis.
# split the concatenated dataset into training and testing sets (80% training, 20% testing)

# write a python program to perform these operations and print the normalized and split datasets.


In [68]:
import numpy as np
from sklearn.model_selection import train_test_split

# Sample datasets
dataset1 = np.array([[1, 2], [3, 4], [5, 6]])
dataset2 = np.array([[7, 8], [9, 10], [11, 12]])

# Step 1: Create numpy arrays from datasets
array1 = np.array(dataset1)
array2 = np.array(dataset2)

# Step 2: Normalize both arrays
normalized_array1 = (array1 - np.mean(array1, axis=0)) / np.std(array1, axis=0)
normalized_array2 = (array2 - np.mean(array2, axis=0)) / np.std(array2, axis=0)

# Step 3: Compute mean and standard deviation for each feature
mean1 = np.mean(array1, axis=0)
std_dev1 = np.std(array1, axis=0)
mean2 = np.mean(array2, axis=0)
std_dev2 = np.std(array2, axis=0)

# Step 4: Subtract means and divide by standard deviation
normalized_dataset1 = (array1 - mean1) / std_dev1
normalized_dataset2 = (array2 - mean2) / std_dev2

# Step 5: Concatenate normalized datasets along column axis
concatenated_dataset = np.concatenate((normalized_dataset1, normalized_dataset2), axis=1)

# Step 6: Split concatenated dataset into training and testing sets
X_train, X_test = train_test_split(concatenated_dataset, test_size=0.2, random_state=42)

# Print the results
print("Normalized Dataset 1:")
print(normalized_dataset1)
print("\nNormalized Dataset 2:")
print(normalized_dataset2)
print("\nConcatenated Dataset:")
print(concatenated_dataset)
print("\nTraining Set:")
print(X_train)
print("\nTesting Set:")
print(X_test)


Normalized Dataset 1:
[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]

Normalized Dataset 2:
[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]

Concatenated Dataset:
[[-1.22474487 -1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487  1.22474487]]

Training Set:
[[0.         0.         0.         0.        ]
 [1.22474487 1.22474487 1.22474487 1.22474487]]

Testing Set:
[[-1.22474487 -1.22474487 -1.22474487 -1.22474487]]


In [26]:
# how to find mean
# mean along axis = 0

dataset2 = np.array([[7, 8], [9, 10], [11, 12]])
np.mean(dataset2,axis= 0)

array([ 9., 10.])

In [ ]:
# sd = x-mu/si

In [41]:
# transpose
a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [43]:
a.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

# matrix multiplication

In [ ]:
b = np.array([[1,2],[3,4]])
c = np.array([[10,20],[30,40]])

In [60]:
b

array([[1, 2],
       [3, 4]])

In [61]:
c

array([[10, 20],
       [30, 40]])

In [62]:
b.dot(c)

array([[ 70, 100],
       [150, 220]])

In [22]:
import numpy as np
arr = np.array([7,6,8,9,10])
newarr = np.sort(arr)
newarr

array([ 6,  7,  8,  9, 10])

In [14]:
import numpy as np
arr = np.array([[7,6,8,10],[7,5,6,10]])
newarr = np.sort(arr, axis = 1)

newarr

array([[ 6,  7,  8, 10],
       [ 5,  6,  7, 10]])

In [23]:
# descending array
import numpy as np
arr = np.array([7, 6, 8, 9, 10])
newarr = np.sort(arr)[::-1]
print(newarr)

[10  9  8  7  6]


In [47]:
import pandas as pd
s = pd.Series(np.array([1,2,3,4,5]))
s

0    1
1    2
2    3
3    4
4    5
dtype: int32

In [33]:
# i mport pandas as pd
# s = pd.Series(np.random.randint([]))
# s

In [44]:
dic = {"a":"python","b":"java","c":"html"}
s1 = pd.Series(dic, index = ["a","b","c","d"])
s1

# index are the keys

a    python
b      java
c      html
d       NaN
dtype: object

In [48]:
# NaN = not a number
# hme pandas me missing value ko impute krna hota hai.
# impute means fill with nearest values


# pandas library is used for data wrangling

In [56]:
dict = {"a":[1,2,3],"b":[5,6,7],"c":[8,9,10]}
s1 = pd.DataFrame(dict)
s1

a  b   c
0  1  5   8
1  2  6   9
2  3  7  10

In [1]:
# for scalar values also pass index


# 6 may 2024

In [2]:
# slicing - part of the 


In [3]:
# isnull.sum() = to check null values in series.

In [5]:
import pandas as pd
data = {"a":[1,2,3],"b":[5,6,7],"c":[8,9,10]}
df = pd.DataFrame(data)
df

a  b   c
0  1  5   8
1  2  6   9
2  3  7  10

In [6]:
df.head()

a  b   c
0  1  5   8
1  2  6   9
2  3  7  10

In [7]:
df.tail()

a  b   c
0  1  5   8
1  2  6   9
2  3  7  10

In [8]:
df.describe()

a    b     c
count  3.0  3.0   3.0
mean   2.0  6.0   9.0
std    1.0  1.0   1.0
min    1.0  5.0   8.0
25%    1.5  5.5   8.5
50%    2.0  6.0   9.0
75%    2.5  6.5   9.5
max    3.0  7.0  10.0

In [9]:
# count() - how many rows in dataset.
# mean - avg (for numerical values only)

In [10]:
# observations describe ke badh likhte hai. yhi pe report bnate hai.
# yha pe hm wo likhenge. 
# hm bar bar upar ni jayenge.

In [19]:
df["a"]

0    1
1    2
2    3
Name: a, dtype: int64

In [41]:
df.loc[["a","c"]]

KeyError: "None of [Index(['a', 'c'], dtype='object')] are in the [index]"

In [24]:
# access 1st row which is at 0th index
df.iloc[0]

a    1
b    5
c    8
Name: 0, dtype: int64

In [27]:
df.loc[0]

a    1
b    5
c    8
Name: 0, dtype: int64

In [32]:
df.loc[:,"a"]  # row column

0    1
1    2
2    3
Name: a, dtype: int64

In [35]:
df

a  b   c
0  1  5   8
1  2  6   9
2  3  7  10

In [48]:
# boolean indexing
df[df["a"]>1]

a  b   c
1  2  6   9
2  3  7  10

In [57]:
def square_sum(row):
    return row['a']**2 + row['b']**2

df['c']=df.apply(square_sum,axis=1)

In [62]:
# add new column
df['d'] = [1,2,3]
df

a  b   c  d
0  1  5  26  1
1  2  6  40  2
2  3  7  58  3

In [70]:
df.drop(["a"], axis = 1)

b   c  d
0  5  26  1
1  6  40  2
2  7  58  3

In [79]:
df.columns

Index(['a', 'b', 'c', 'd'], dtype='object')

In [85]:
# sorting is important
df.sort_values(by='a')

a  b   c  d
0  1  5  26  1
1  2  6  40  2
2  3  7  58  3

In [86]:
import pandas as pd
data = {"a":[2,1,3],"b":[6,3,9],"c":[8,9,10]}
df1 = pd.DataFrame(data)
df1

a  b   c
0  1  5   8
1  2  6   9
2  3  7  10